### ISSUE TITLE
Robotiq 2F controller

### ISSUE THREAD

**Issue by caiobarrosv** [ipa-rwu/ur5_2f_webots#2]
Dear @ipa-rwu,

did you manage to control both fingers of the Robotiq 2F?

If yes, could you please explain me how did you implement this?

Thank you in advance :)

**Comment by caiobarrosv** [comment]
I finally did it!

I sent a individual command to each joint defined in robotiq.proto.

It works!

Thanks anyway! Your repo helped me a lot!

**Comment by ipa-rwu** [comment]
@caiobarrosv It is nice that you make it!. For me, I only control one joint of Robotiq 2F. The driver I coded  publishes gripper joint states and served as an action server for gripper trajectory server

**Comment by caiobarrosv** [comment]
@ipa-rwu, it is a nice solution. Thank you. I'll close this issue since it is solved :)
